### ISSUE TITLE
Example of use inside code doesn't quite work

### ISSUE THREAD

**Issue by WalterCJ** [Xotic750/replace-x#3]
I tried to run the example below and didn't work:

```javascript
var replace = require('replace-x');

replace({
    regex: 'foo',
    replacement: 'bar',
    paths: ['../test/File.txt']
});
```

I notice if you change to this works fine:
```javascript
var replace = require('replace-x').default;
```

**Comment by Xotic750** [comment]
Yes, that is normal as I have changed the code to be ESM. I have been updating the docs to show ESM examples using ìmport`, clearly I missed this one :)

**Comment by Xotic750** [comment]
Ok, I have changed the example in the README. But yes, when using CJS `default` is required.
